version: 1
formatters:
    simple:
        format: '%(name)s: %(levelname)s: %(message)s'
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout
    info_file:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: info.log
        maxBytes: 10485760
        backupCount: 20
        encoding: utf8
    error_file:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: error.log
        maxBytes: 10485760
        backupCount: 20
        encoding: utf8
loggers:
    data_handlers:
        level: INFO
        handlers: [console,info_file]
        propagate: no
root:
    level: DEBUG
    handlers: [console,info_file]
